import { createHash } from 'node:crypto';

export type ScaffoldTarget = 'web' | 'backend' | 'full-stack';
export type ScaffoldLanguage = 'typescript' | 'javascript' | 'python' | 'java' | 'go';
export type ScaffoldFramework =
  | 'react'
  | 'nextjs'
  | 'vue'
  | 'svelte'
  | 'express'
  | 'fastapi'
  | 'spring-boot'
  | 'gin'
  | 'unknown';
export type ConflictPolicy = 'never' | 'changed-only' | 'all';
export type ScaffoldPermissionDecision = 'ALLOW' | 'ASK' | 'DENY';

export interface ScaffoldPermissionPolicy {
  decide(request: {
    capability: 'filesystem.write';
    resource?: string;
    reason: string;
  }): ScaffoldPermissionDecision;
}

export interface TemplateDefinition {
  id: string;
  version: number;
  name: string;
  description: string;
  targets: ScaffoldTarget[];
  languages: ScaffoldLanguage[];
  frameworks: ScaffoldFramework[];
}

export interface ScaffoldSpec {
  id: string;
  name: string;
  description: string;
  target: ScaffoldTarget;
  language: ScaffoldLanguage;
  framework: ScaffoldFramework;
  revision: number;
  templateId: string;
  templateVersion?: number;
  variables?: Record<string, string>;
}

export interface ScaffoldFile {
  path: string;
  content: string;
  checksum: string;
}

export interface ScaffoldPlan {
  schemaVersion: 1;
  templateId: string;
  templateVersion: number;
  specId: string;
  revision: number;
  parametersChecksum: string;
  directories: string[];
  files: ScaffoldFile[];
  checksum: string;
}

export interface ScaffoldValidationIssue {
  code: string;
  field: string;
  message: string;
}

export interface ScaffoldAdapter {
  readExistingPaths(paths: string[]): Promise<Record<string, string | undefined>>;
  apply(plan: ScaffoldPlan, conflictPolicy: ConflictPolicy): Promise<ScaffoldApplyResult>;
}

export interface ScaffoldApplyResult {
  status: 'APPLIED' | 'BLOCKED';
  written: string[];
  skipped: string[];
  diagnostics: string[];
}

export interface ScaffoldApproval {
  approved: boolean;
  planChecksum: string;
}

const ID_PATTERN = /^[a-z][a-z0-9-]{1,62}$/;
const SAFE_PATH = /^(?!\/)(?!.*(?:^|\/)\.\.?\/?)(?!.*(?:^|\/)\.git(?:\/|$))[A-Za-z0-9._/-]+$/;
const MAX_FILES = 500;
const MAX_CONTENT = 2_000_000;

const registry: TemplateDefinition[] = [
  { id: 'web-nextjs', version: 1, name: 'Next.js Web Application', description: 'Minimal full-stack web application scaffold using Next.js.', targets: ['web', 'full-stack'], languages: ['typescript', 'javascript'], frameworks: ['nextjs'] },
  { id: 'web-react-vite', version: 1, name: 'React Vite Web Application', description: 'Minimal browser application scaffold using React and Vite.', targets: ['web'], languages: ['typescript', 'javascript'], frameworks: ['react'] },
  { id: 'backend-fastapi', version: 1, name: 'FastAPI Service', description: 'Minimal Python API scaffold using FastAPI.', targets: ['backend'], languages: ['python'], frameworks: ['fastapi'] },
  { id: 'backend-spring-boot', version: 1, name: 'Spring Boot Service', description: 'Minimal Java API scaffold using Spring Boot.', targets: ['backend'], languages: ['java'], frameworks: ['spring-boot'] },
  { id: 'backend-go', version: 1, name: 'Go API Service', description: 'Minimal Go API scaffold using Gin.', targets: ['backend'], languages: ['go'], frameworks: ['gin'] },
];

function sha256(value: string): string {
  return createHash('sha256').update(value, 'utf8').digest('hex');
}

function canonical(value: unknown): string {
  return JSON.stringify(value);
}

function escapeHtml(value: string): string {
  return value.replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[character] ?? character);
}

function templateFiles(spec: ScaffoldSpec): Array<{ path: string; content: string }> {
  const name = escapeHtml(spec.name);
  const description = escapeHtml(spec.description);
  const appId = JSON.stringify(spec.id);
  const files: Array<{ path: string; content: string }> = [
    { path: 'README.md', content: `# ${spec.name}\n\n${spec.description}\n\nGenerated by INFINITY-11 template ${spec.templateId}@${spec.templateVersion ?? 1}.\n` },
    { path: '.gitignore', content: 'node_modules/\ndist/\ncoverage/\n.env\n.env.*\n!.env.example\n__pycache__/\n.venv/\n' },
    { path: '.env.example', content: '# Configuration names only. Never commit credentials.\n' },
  ];

  switch (spec.templateId) {
    case 'web-nextjs':
      files.push(
        { path: 'package.json', content: JSON.stringify({ name: spec.id, version: '0.1.0', private: true, type: 'module', scripts: { dev: 'next dev', build: 'next build', test: 'vitest run', lint: 'eslint .' }, dependencies: { next: '15.5.2', react: '19.1.1', 'react-dom': '19.1.1' }, devDependencies: { typescript: '5.9.2', vitest: '3.2.6' } }, null, 2) + '\n' },
        { path: 'src/app/page.tsx', content: `export default function Home() {\n  return <main><h1>${name}</h1><p>${description}</p></main>;\n}\n` },
        { path: 'src/app/api/health/route.ts', content: `export function GET() {\n  return Response.json({ status: 'ok', application: ${appId} });\n}\n` },
        { path: 'tests/smoke.test.ts', content: "import { describe, expect, it } from 'vitest';\n\ndescribe('scaffold', () => {\n  it('is deterministic', () => expect(true).toBe(true));\n});\n" },
      );
      break;
    case 'web-react-vite':
      files.push(
        { path: 'package.json', content: JSON.stringify({ name: spec.id, version: '0.1.0', private: true, type: 'module', scripts: { dev: 'vite', build: 'vite build', test: 'vitest run' }, dependencies: { react: '19.1.1', 'react-dom': '19.1.1' }, devDependencies: { vite: '7.1.3', typescript: '5.9.2', vitest: '3.2.6' } }, null, 2) + '\n' },
        { path: 'index.html', content: `<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>${name}</title></head><body><div id="root"></div><script type="module" src="/src/main.tsx"></script></body></html>\n` },
        { path: 'src/App.tsx', content: `export function App() {\n  return <main><h1>${name}</h1><p>${description}</p></main>;\n}\n` },
        { path: 'src/main.tsx', content: "import { createRoot } from 'react-dom/client';\nimport { App } from './App';\n\ncreateRoot(document.getElementById('root')!).render(<App />);\n" },
      );
      break;
    case 'backend-fastapi':
      files.push({ path: 'app/main.py', content: `from fastapi import FastAPI\n\napp = FastAPI(title=${JSON.stringify(spec.name)})\n\n@app.get('/health')\ndef health() -> dict[str, str]:\n    return {'status': 'ok', 'application': ${JSON.stringify(spec.id)}}\n` });
      break;
    case 'backend-spring-boot':
      files.push(
        { path: 'src/main/java/com/infinity11/Application.java', content: `package com.infinity11;\n\nimport org.springframework.boot.SpringApplication;\nimport org.springframework.boot.autoconfigure.SpringBootApplication;\n\n@SpringBootApplication\npublic class Application {\n  public static void main(String[] args) { SpringApplication.run(Application.class, args); }\n}\n` },
        { path: 'src/main/java/com/infinity11/HealthController.java', content: `package com.infinity11;\n\nimport java.util.Map;\nimport org.springframework.web.bind.annotation.GetMapping;\nimport org.springframework.web.bind.annotation.RestController;\n\n@RestController\npublic class HealthController {\n  @GetMapping("/health")\n  public Map<String, String> health() { return Map.of("status", "ok", "application", ${JSON.stringify(spec.id)}); }\n}\n` },
      );
      break;
    case 'backend-go':
      files.push({ path: 'cmd/server/main.go', content: `package main\n\nimport "github.com/gin-gonic/gin"\n\nfunc main() {\n  r := gin.Default()\n  r.GET("/health", func(c *gin.Context) { c.JSON(200, gin.H{"status": "ok", "application": ${JSON.stringify(spec.id)}}) })\n  r.Run()\n}\n` });
      break;
    default:
      throw new Error(`Unknown template: ${spec.templateId}`);
  }
  return files;
}

export function listTemplates(): TemplateDefinition[] {
  return registry.map((template) => ({ ...template, targets: [...template.targets], languages: [...template.languages], frameworks: [...template.frameworks] }));
}

export function getTemplate(id: string): TemplateDefinition | undefined {
  const template = registry.find((candidate) => candidate.id === id);
  return template ? { ...template, targets: [...template.targets], languages: [...template.languages], frameworks: [...template.frameworks] } : undefined;
}

export function validateScaffoldSpec(spec: ScaffoldSpec): ScaffoldValidationIssue[] {
  const issues: ScaffoldValidationIssue[] = [];
  if (!ID_PATTERN.test(spec.id)) issues.push({ code: 'INVALID_ID', field: 'id', message: 'Id must be 2–63 lowercase characters, digits, or hyphens and start with a letter.' });
  if (!spec.name.trim()) issues.push({ code: 'NAME_REQUIRED', field: 'name', message: 'Application name is required.' });
  if (!spec.description.trim()) issues.push({ code: 'DESCRIPTION_REQUIRED', field: 'description', message: 'Application description is required.' });
  if (!Number.isInteger(spec.revision) || spec.revision < 1) issues.push({ code: 'INVALID_REVISION', field: 'revision', message: 'Revision must be a positive integer.' });
  const template = getTemplate(spec.templateId);
  if (!template) return [...issues, { code: 'TEMPLATE_NOT_FOUND', field: 'templateId', message: `Unknown template: ${spec.templateId}.` }];
  const version = spec.templateVersion ?? template.version;
  if (version !== template.version) issues.push({ code: 'TEMPLATE_VERSION_UNSUPPORTED', field: 'templateVersion', message: `Template ${template.id} only supports version ${template.version}.` });
  if (!template.targets.includes(spec.target)) issues.push({ code: 'TARGET_UNSUPPORTED', field: 'target', message: `Template ${template.id} does not support ${spec.target}.` });
  if (!template.languages.includes(spec.language)) issues.push({ code: 'LANGUAGE_UNSUPPORTED', field: 'language', message: `Template ${template.id} does not support ${spec.language}.` });
  if (!template.frameworks.includes(spec.framework)) issues.push({ code: 'FRAMEWORK_UNSUPPORTED', field: 'framework', message: `Template ${template.id} does not support ${spec.framework}.` });
  for (const [key, value] of Object.entries(spec.variables ?? {})) {
    if (!/^[A-Za-z][A-Za-z0-9_-]{0,63}$/.test(key)) issues.push({ code: 'VARIABLE_KEY_INVALID', field: `variables.${key}`, message: 'Variable keys must be identifier-like.' });
    if (value.length > 100_000) issues.push({ code: 'VARIABLE_TOO_LARGE', field: `variables.${key}`, message: 'Variable values must not exceed 100,000 characters.' });
  }
  return issues;
}

export function createScaffoldPlan(spec: ScaffoldSpec): ScaffoldPlan {
  const issues = validateScaffoldSpec(spec);
  if (issues.length) throw new Error(`Invalid scaffold specification: ${issues.map((issue) => issue.code).join(', ')}`);
  const template = getTemplate(spec.templateId);
  if (!template) throw new Error('Template disappeared during validation.');
  const files = templateFiles({ ...spec, templateVersion: template.version });
  if (files.length > MAX_FILES) throw new Error('Template exceeds maximum file count.');
  const scaffoldFiles: ScaffoldFile[] = files.map((file) => {
    if (!SAFE_PATH.test(file.path) || file.path.startsWith('node_modules/')) throw new Error(`Unsafe generated path: ${file.path}`);
    if (file.content.length > MAX_CONTENT) throw new Error(`Generated file is too large: ${file.path}`);
    return { path: file.path, content: file.content, checksum: sha256(file.content) };
  }).sort((a, b) => a.path.localeCompare(b.path));
  const parameters = { ...spec, templateVersion: template.version, variables: Object.fromEntries(Object.entries(spec.variables ?? {}).sort(([a], [b]) => a.localeCompare(b))) };
  const parametersChecksum = sha256(canonical(parameters));
  const directories = [...new Set(scaffoldFiles.flatMap((file) => {
    const parts = file.path.split('/');
    const result: string[] = [];
    for (let index = 1; index < parts.length; index += 1) result.push(parts.slice(0, index).join('/'));
    return result;
  }))].sort();
  const checksum = sha256(canonical({ templateId: template.id, templateVersion: template.version, specId: spec.id, revision: spec.revision, parametersChecksum, directories, files: scaffoldFiles.map(({ path, checksum: fileChecksum }) => ({ path, checksum: fileChecksum })) }));
  return { schemaVersion: 1, templateId: template.id, templateVersion: template.version, specId: spec.id, revision: spec.revision, parametersChecksum, directories, files: scaffoldFiles, checksum };
}

export async function applyScaffold(plan: ScaffoldPlan, adapter: ScaffoldAdapter, policy: ScaffoldPermissionPolicy, conflictPolicy: ConflictPolicy, approval?: ScaffoldApproval): Promise<ScaffoldApplyResult> {
  if (plan.schemaVersion !== 1 || !plan.checksum || plan.files.some((file) => !SAFE_PATH.test(file.path) || sha256(file.content) !== file.checksum)) return { status: 'BLOCKED', written: [], skipped: [], diagnostics: ['INVALID_PLAN'] };
  const decision = policy.decide({ capability: 'filesystem.write', resource: plan.specId, reason: `Apply scaffold ${plan.templateId}@${plan.templateVersion}.` });
  if (decision === 'DENY') return { status: 'BLOCKED', written: [], skipped: [], diagnostics: ['POLICY_DENIED'] };
  if (decision === 'ASK' && (!approval?.approved || approval.planChecksum !== plan.checksum)) return { status: 'BLOCKED', written: [], skipped: [], diagnostics: ['APPROVAL_REQUIRED'] };
  const existing = await adapter.readExistingPaths(plan.files.map((file) => file.path));
  if (conflictPolicy === 'never' && Object.values(existing).some((value) => value !== undefined)) return { status: 'BLOCKED', written: [], skipped: [], diagnostics: ['CONFLICTS_PRESENT'] };
  if (conflictPolicy === 'changed-only') {
    const changedPlan: ScaffoldPlan = { ...plan, files: plan.files.filter((file) => existing[file.path] !== file.content) };
    return adapter.apply(changedPlan, conflictPolicy);
  }
  return adapter.apply(plan, conflictPolicy);
}
