export type GenerationTarget = 'web' | 'backend' | 'full-stack';
export type GenerationLanguage = 'typescript' | 'javascript' | 'python' | 'java' | 'go';
export type GenerationFramework =
  | 'react'
  | 'nextjs'
  | 'vue'
  | 'svelte'
  | 'express'
  | 'fastapi'
  | 'spring-boot'
  | 'gin'
  | 'unknown';

export interface GenerationRequirement {
  id: string;
  description: string;
  acceptanceCriteria: string[];
  priority: 'must' | 'should' | 'could';
}
export interface GenerationSpec {
  id: string;
  name: string;
  description: string;
  targets: GenerationTarget[];
  language: GenerationLanguage;
  framework: GenerationFramework;
  requirements: GenerationRequirement[];
  constraints: string[];
  revision: number;
}
export interface GeneratedFile {
  path: string;
  content: string;
  purpose: string;
  generated: true;
}
export interface GeneratedProjectManifest {
  schemaVersion: 1;
  generator: 'infinity-11-full-stack-codegen';
  specId: string;
  revision: number;
  language: GenerationLanguage;
  framework: GenerationFramework;
  targets: GenerationTarget[];
  files: string[];
  commands: string[];
  requirementTraceability: Record<string, string[]>;
}
export interface GeneratedProject {
  manifest: GeneratedProjectManifest;
  files: GeneratedFile[];
  audit: GenerationAudit;
}
export interface GenerationAudit {
  passed: boolean;
  errors: string[];
  warnings: string[];
  checks: string[];
}

const safeId = /^[a-z][a-z0-9-]{1,62}$/;
const allowed = <T extends string>(value: T, values: readonly T[]) => values.includes(value);
const targets: GenerationTarget[] = ['web', 'backend', 'full-stack'];
const languages: GenerationLanguage[] = ['typescript', 'javascript', 'python', 'java', 'go'];
const frameworks: GenerationFramework[] = [
  'react',
  'nextjs',
  'vue',
  'svelte',
  'express',
  'fastapi',
  'spring-boot',
  'gin',
  'unknown',
];
const frameworkLanguages: Record<GenerationFramework, GenerationLanguage[]> = {
  react: ['typescript', 'javascript'],
  nextjs: ['typescript', 'javascript'],
  vue: ['typescript', 'javascript'],
  svelte: ['typescript', 'javascript'],
  express: ['typescript', 'javascript'],
  fastapi: ['python'],
  'spring-boot': ['java'],
  gin: ['go'],
  unknown: languages,
};

export function validateGenerationSpec(spec: GenerationSpec): string[] {
  const errors: string[] = [];
  if (!safeId.test(spec.id)) errors.push('INVALID_APPLICATION_ID');
  if (!spec.name.trim()) errors.push('APPLICATION_NAME_REQUIRED');
  if (!spec.description.trim()) errors.push('APPLICATION_DESCRIPTION_REQUIRED');
  if (!spec.targets.length || spec.targets.some((target) => !allowed(target, targets)))
    errors.push('INVALID_TARGET');
  if (!allowed(spec.language, languages)) errors.push('UNSUPPORTED_LANGUAGE');
  if (!allowed(spec.framework, frameworks)) errors.push('UNSUPPORTED_FRAMEWORK');
  if (
    allowed(spec.framework, frameworks) &&
    !frameworkLanguages[spec.framework].includes(spec.language)
  )
    errors.push('FRAMEWORK_LANGUAGE_MISMATCH');
  if (!Number.isInteger(spec.revision) || spec.revision < 1) errors.push('INVALID_REVISION');
  if (!spec.requirements.length) errors.push('REQUIREMENTS_REQUIRED');
  const ids = new Set<string>();
  for (const requirement of spec.requirements) {
    if (!requirement.id.trim()) errors.push('REQUIREMENT_ID_REQUIRED');
    else if (ids.has(requirement.id.trim()))
      errors.push(`DUPLICATE_REQUIREMENT:${requirement.id.trim()}`);
    ids.add(requirement.id.trim());
    if (!requirement.description.trim())
      errors.push(`REQUIREMENT_DESCRIPTION_REQUIRED:${requirement.id.trim()}`);
    if (!requirement.acceptanceCriteria.length)
      errors.push(`ACCEPTANCE_CRITERIA_REQUIRED:${requirement.id.trim()}`);
  }
  if (
    spec.targets.includes('full-stack') &&
    !['nextjs', 'express', 'fastapi', 'spring-boot', 'gin', 'unknown'].includes(spec.framework)
  ) {
    errors.push('FULL_STACK_FRAMEWORK_UNSUPPORTED');
  }
  return [...new Set(errors)];
}

function json(value: unknown): string {
  return JSON.stringify(value, null, 2) + '\n';
}
function requirementsMarkdown(spec: GenerationSpec): string {
  return `# ${spec.name}\n\n${spec.description}\n\n## Requirements\n\n${spec.requirements.map((r) => `### ${r.id}\n\n- Priority: ${r.priority}\n- ${r.description}\n- Acceptance: ${r.acceptanceCriteria.join('; ')}`).join('\n\n')}\n`;
}
function baseFiles(spec: GenerationSpec): GeneratedFile[] {
  return [
    {
      path: 'README.md',
      purpose: 'Project setup, generated boundary, and verification contract.',
      generated: true,
      content: `# ${spec.name}\n\n${spec.description}\n\nGenerated by INFINITY-11 Full-Stack Code Generation. Run the documented install, test, lint, and build commands before delivery.\n`,
    },
    {
      path: '.gitignore',
      purpose: 'Exclude build output, dependencies, and local secrets.',
      generated: true,
      content: `node_modules/\ndist/\ncoverage/\n.env\n.env.*\n!.env.example\n__pycache__/\n.venv/\n`,
    },
    {
      path: '.env.example',
      purpose: 'Document configuration names without embedding credentials.',
      generated: true,
      content: `# Add non-secret configuration names here. Never commit credentials.\n`,
    },
    {
      path: 'docs/requirements.md',
      purpose: 'Traceable application requirements.',
      generated: true,
      content: requirementsMarkdown(spec),
    },
  ];
}
function tsPackage(
  name: string,
  scripts: Record<string, string>,
  dependencies: Record<string, string> = {},
  devDependencies: Record<string, string> = {},
): GeneratedFile {
  return {
    path: 'package.json',
    purpose: 'Deterministic project package metadata and commands.',
    generated: true,
    content: json({
      name,
      version: '0.1.0',
      private: true,
      type: 'module',
      scripts,
      dependencies,
      devDependencies,
      engines: { node: '>=22.14.0 <23' },
    }),
  };
}
function tsConfig(): GeneratedFile {
  return {
    path: 'tsconfig.json',
    purpose: 'Strict TypeScript compilation boundary for generated source.',
    generated: true,
    content: json({
      compilerOptions: {
        target: 'ES2022',
        module: 'NodeNext',
        moduleResolution: 'NodeNext',
        strict: true,
        noUncheckedIndexedAccess: true,
        noEmit: true,
        jsx: 'react-jsx',
        types: ['node'],
      },
      include: ['src/**/*.ts', 'src/**/*.tsx', 'tests/**/*.ts'],
    }),
  };
}
function tsSmoke(): GeneratedFile {
  return {
    path: 'tests/smoke.test.ts',
    purpose: 'Deterministic generated-project health check.',
    generated: true,
    content: `import { describe, expect, it } from 'vitest';\n\ndescribe('generated project smoke test', () => {\n  it('has a stable generation contract', () => {\n    expect(true).toBe(true);\n  });\n});\n`,
  };
}
function addWebFiles(files: GeneratedFile[], spec: GenerationSpec): void {
  if (spec.framework === 'nextjs') {
    files.push({
      path: 'src/app/page.tsx',
      purpose: 'Generated web entry screen.',
      generated: true,
      content: `export default function Home() {\n  return <main><h1>${spec.name}</h1><p>${spec.description}</p></main>;\n}\n`,
    });
    files.push({
      path: 'src/app/api/health/route.ts',
      purpose: 'Generated backend health endpoint for the full-stack web runtime.',
      generated: true,
      content: `export function GET() {\n  return Response.json({ status: 'ok' });\n}\n`,
    });
  } else if (
    spec.framework === 'react' ||
    spec.framework === 'vue' ||
    spec.framework === 'svelte'
  ) {
    const ext = spec.framework === 'react' ? 'tsx' : spec.framework === 'vue' ? 'vue' : 'svelte';
    const content =
      spec.framework === 'react'
        ? `export function App() {\n  return <main><h1>${spec.name}</h1><p>${spec.description}</p></main>;\n}\n`
        : spec.framework === 'vue'
          ? `<template><main><h1>${spec.name}</h1><p>${spec.description}</p></main></template>\n`
          : `<main><h1>${spec.name}</h1><p>${spec.description}</p></main>\n`;
    files.push({
      path: `src/App.${ext}`,
      purpose: 'Generated web application entry component.',
      generated: true,
      content,
    });
    if (spec.framework === 'react') {
      files.push({
        path: 'index.html',
        purpose: 'Generated browser entry document.',
        generated: true,
        content: `<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>${spec.name}</title></head><body><div id="app"></div><script type="module" src="/src/main.tsx"></script></body></html>\n`,
      });
      files.push({
        path: 'src/main.tsx',
        purpose: 'Generated browser bootstrap.',
        generated: true,
        content: `import React from 'react';\nimport { createRoot } from 'react-dom/client';\nimport { App } from './App';\n\ncreateRoot(document.getElementById('app')!).render(<React.StrictMode><App /></React.StrictMode>);\n`,
      });
    }
  }
}
function addBackendFiles(files: GeneratedFile[], spec: GenerationSpec): void {
  if (spec.framework === 'express')
    files.push({
      path: 'src/server.ts',
      purpose: 'Generated HTTP server boundary.',
      generated: true,
      content: `import { createServer } from 'node:http';\n\nconst server = createServer((_req, res) => {\n  res.setHeader('content-type', 'application/json');\n  res.end(JSON.stringify({ status: 'ok', application: '${spec.id}' }));\n});\n\nserver.listen(Number(process.env.PORT ?? 3000));\n`,
    });
  else if (spec.framework === 'fastapi')
    files.push({
      path: 'app/main.py',
      purpose: 'Generated FastAPI application boundary.',
      generated: true,
      content: `from fastapi import FastAPI\n\napp = FastAPI(title=${JSON.stringify(spec.name)})\n\n@app.get('/health')\ndef health() -> dict[str, str]:\n    return {'status': 'ok'}\n`,
    });
  else if (spec.framework === 'spring-boot') {
    files.push({
      path: 'src/main/java/com/infinity11/Application.java',
      purpose: 'Generated Spring Boot application boundary.',
      generated: true,
      content: `package com.infinity11;\n\nimport org.springframework.boot.SpringApplication;\nimport org.springframework.boot.autoconfigure.SpringBootApplication;\n\n@SpringBootApplication\npublic class Application {\n  public static void main(String[] args) { SpringApplication.run(Application.class, args); }\n}\n`,
    });
    files.push({
      path: 'src/main/java/com/infinity11/HealthController.java',
      purpose: 'Generated health endpoint.',
      generated: true,
      content: `package com.infinity11;\n\nimport java.util.Map;\nimport org.springframework.web.bind.annotation.GetMapping;\nimport org.springframework.web.bind.annotation.RestController;\n\n@RestController\npublic class HealthController {\n  @GetMapping("/health")\n  public Map<String, String> health() { return Map.of("status", "ok"); }\n}\n`,
    });
  } else if (spec.framework === 'gin')
    files.push({
      path: 'cmd/server/main.go',
      purpose: 'Generated Gin server boundary.',
      generated: true,
      content: `package main\n\nimport "github.com/gin-gonic/gin"\n\nfunc main() {\n  r := gin.Default()\n  r.GET("/health", func(c *gin.Context) { c.JSON(200, gin.H{"status": "ok"}) })\n  r.Run()\n}\n`,
    });
}

export function generateProject(spec: GenerationSpec): GeneratedProject {
  const errors = validateGenerationSpec(spec);
  if (errors.length) throw new Error(`Invalid generation specification: ${errors.join(', ')}`);
  const files = baseFiles(spec);
  if (spec.targets.includes('web') || spec.targets.includes('full-stack')) addWebFiles(files, spec);
  if (spec.targets.includes('backend') || spec.targets.includes('full-stack'))
    addBackendFiles(files, spec);
  if (spec.framework === 'nextjs')
    files.push(
      tsPackage(
        spec.id,
        {
          dev: 'next dev',
          build: 'next build',
          test: 'vitest run',
          lint: 'eslint .',
          typecheck: 'tsc --noEmit',
        },
        { next: '15.5.2', react: '19.1.1', 'react-dom': '19.1.1' },
        {
          '@types/node': '22.18.6',
          '@types/react': '19.1.12',
          '@types/react-dom': '19.1.9',
          eslint: '9.35.0',
          typescript: '5.9.2',
          vitest: '3.2.6',
        },
      ),
      tsConfig(),
      tsSmoke(),
    );
  else if (spec.framework === 'react')
    files.push(
      tsPackage(
        spec.id,
        {
          dev: 'vite',
          build: 'vite build',
          test: 'vitest run',
          lint: 'eslint .',
          typecheck: 'tsc --noEmit',
        },
        { react: '19.1.1', 'react-dom': '19.1.1' },
        {
          '@vitejs/plugin-react': '5.0.2',
          '@types/react': '19.1.12',
          '@types/react-dom': '19.1.9',
          eslint: '9.35.0',
          typescript: '5.9.2',
          vite: '7.1.3',
          vitest: '3.2.6',
        },
      ),
      {
        path: 'vite.config.ts',
        purpose: 'Deterministic Vite configuration.',
        generated: true,
        content: `import { defineConfig } from 'vite';\nimport react from '@vitejs/plugin-react';\n\nexport default defineConfig({ plugins: [react()] });\n`,
      },
      tsConfig(),
      tsSmoke(),
    );
  else if (spec.framework === 'vue')
    files.push(
      tsPackage(
        spec.id,
        {
          dev: 'vite',
          build: 'vite build',
          test: 'vitest run',
          lint: 'eslint .',
          typecheck: 'tsc --noEmit',
        },
        { vue: '3.5.21' },
        {
          '@vitejs/plugin-vue': '6.0.1',
          typescript: '5.9.2',
          vite: '7.1.3',
          vitest: '3.2.6',
          vue: '3.5.21',
        },
      ),
      {
        path: 'vite.config.ts',
        purpose: 'Deterministic Vite configuration.',
        generated: true,
        content: `import { defineConfig } from 'vite';\nimport vue from '@vitejs/plugin-vue';\n\nexport default defineConfig({ plugins: [vue()] });\n`,
      },
      tsConfig(),
      tsSmoke(),
    );
  else if (spec.framework === 'svelte')
    files.push(
      tsPackage(
        spec.id,
        {
          dev: 'vite',
          build: 'vite build',
          test: 'vitest run',
          lint: 'eslint .',
          typecheck: 'tsc --noEmit',
        },
        { '@sveltejs/vite-plugin-svelte': '6.1.0', svelte: '5.38.7' },
        { typescript: '5.9.2', vite: '7.1.3', vitest: '3.2.6' },
      ),
      {
        path: 'vite.config.ts',
        purpose: 'Deterministic Vite configuration.',
        generated: true,
        content: `import { defineConfig } from 'vite';\nimport { svelte } from '@sveltejs/vite-plugin-svelte';\n\nexport default defineConfig({ plugins: [svelte()] });\n`,
      },
      tsConfig(),
      tsSmoke(),
    );
  else if (spec.framework === 'express')
    files.push(
      tsPackage(
        spec.id,
        {
          dev: 'tsx src/server.ts',
          build: 'tsc -p tsconfig.json',
          test: 'vitest run',
          lint: 'eslint .',
          typecheck: 'tsc --noEmit',
        },
        {},
        {
          '@types/node': '22.18.6',
          eslint: '9.35.0',
          tsx: '4.20.5',
          typescript: '5.9.2',
          vitest: '3.2.6',
        },
      ),
      tsConfig(),
      tsSmoke(),
    );
  else if (spec.framework === 'fastapi')
    files.push(
      {
        path: 'pyproject.toml',
        purpose: 'Python project metadata and test configuration.',
        generated: true,
        content: `[project]\nname = "${spec.id}"\nversion = "0.1.0"\ndependencies = ["fastapi"]\n\n[tool.pytest.ini_options]\ntestpaths = ["tests"]\n`,
      },
      {
        path: 'tests/test_health.py',
        purpose: 'Generated backend smoke test contract.',
        generated: true,
        content: `def test_health_contract() -> None:\n    assert {'status': 'ok'}['status'] == 'ok'\n`,
      },
    );
  else if (spec.framework === 'spring-boot')
    files.push({
      path: 'pom.xml',
      purpose: 'Generated Maven build contract with Spring Web runtime.',
      generated: true,
      content: `<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd"><modelVersion>4.0.0</modelVersion><parent><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-parent</artifactId><version>3.5.5</version></parent><groupId>com.infinity11</groupId><artifactId>${spec.id}</artifactId><version>0.1.0</version><properties><java.version>21</java.version></properties><dependencies><dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-web</artifactId></dependency><dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-test</artifactId><scope>test</scope></dependency></dependencies><build><plugins><plugin><groupId>org.springframework.boot</groupId><artifactId>spring-boot-maven-plugin</artifactId></plugin></plugins></build></project>\n`,
    });
  else if (spec.framework === 'gin')
    files.push({
      path: 'go.mod',
      purpose: 'Generated Go module contract.',
      generated: true,
      content: `module ${spec.id}\n\ngo 1.23\n\nrequire github.com/gin-gonic/gin v1.10.0\n`,
    });
  else
    files.push({
      path: 'src/main.txt',
      purpose: 'Generated framework-neutral source boundary.',
      generated: true,
      content: `${spec.name}\n${spec.description}\n`,
    });

  const paths = files.map((file) => file.path);
  const requirementTraceability = Object.fromEntries(
    spec.requirements.map((r) => [r.id.trim(), paths]),
  );
  const commands = ['install', 'dev', 'build', 'test', 'lint', 'typecheck', 'security'];
  const manifest: GeneratedProjectManifest = {
    schemaVersion: 1,
    generator: 'infinity-11-full-stack-codegen',
    specId: spec.id,
    revision: spec.revision,
    language: spec.language,
    framework: spec.framework,
    targets: [...new Set(spec.targets)],
    files: [...paths].sort(),
    commands,
    requirementTraceability,
  };
  files.push({
    path: 'infinity-11.generated.json',
    purpose: 'Machine-readable generation and traceability manifest.',
    generated: true,
    content: json(manifest),
  });
  files.sort((a, b) => a.path.localeCompare(b.path));
  const audit = auditGeneratedProject({ manifest, files });
  if (!audit.passed) throw new Error(`Generated project audit failed: ${audit.errors.join('; ')}`);
  return { manifest, files, audit };
}

export function auditGeneratedProject(project: Omit<GeneratedProject, 'audit'>): GenerationAudit {
  const errors: string[] = [];
  const warnings: string[] = [];
  const checks: string[] = [];
  const seen = new Set<string>();
  for (const file of project.files) {
    if (seen.has(file.path)) errors.push(`DUPLICATE_PATH:${file.path}`);
    seen.add(file.path);
    if (
      !file.path ||
      file.path.startsWith('/') ||
      file.path.includes('\\') ||
      file.path.split('/').includes('..') ||
      file.path.includes('\0')
    )
      errors.push(`UNSAFE_PATH:${file.path}`);
    if (/^(\.env$|.*\.pem$|.*\.key$|id_rsa$)/i.test(file.path))
      errors.push(`SECRET_FILE:${file.path}`);
    if (
      /-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----|(?:sk|api|token)[-_]?[A-Za-z0-9]{16,}/i.test(
        file.content,
      )
    )
      errors.push(`POSSIBLE_SECRET:${file.path}`);
  }
  const required = [
    'README.md',
    '.gitignore',
    '.env.example',
    'docs/requirements.md',
    'infinity-11.generated.json',
  ];
  for (const path of required) if (!seen.has(path)) errors.push(`MISSING_REQUIRED_FILE:${path}`);
  if (!project.manifest.files.every((path) => seen.has(path)))
    errors.push('MANIFEST_FILE_MISMATCH');
  for (const [id, paths] of Object.entries(project.manifest.requirementTraceability))
    if (!id.trim() || !paths.length) errors.push(`INVALID_TRACEABILITY:${id}`);
  for (const command of ['install', 'dev', 'build', 'test', 'lint', 'typecheck', 'security'])
    if (!project.manifest.commands.includes(command)) errors.push(`MISSING_COMMAND:${command}`);
  checks.push('unique paths');
  checks.push('path traversal protection');
  checks.push('secret-file/content scan');
  checks.push('required project contract');
  checks.push('manifest consistency');
  checks.push('requirement traceability');
  return { passed: errors.length === 0, errors, warnings, checks };
}
